version: "3"

services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    networks:
      - fix_network
  client:
    build:
      context: ./client
    networks:
      - fix_network
    depends_on:
      - server

networks:
  fix_network:
